export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGOUT = "LOGOUT"

export const GET_PRODUCT="GET_PRODUCT"
export const GET_CATEGORY="GET_CATEGORY"
export const GET_SUBCATEGORY="GET_SUBCATEGORY"
export const ADD_PARENT_CATEGORY="ADD_PARENT_CATEGORY" //PARENT EKLEMEK İÇİN 
export const ADD_SUB_CATEGORY="ADD_SUB_CATEGORY"
export const ADD_PRODUCT ="ADD_PRODUCT"
export const PUT_CATEGORY ="PUT_CATEGORY"
export const PUT_SUBCATEGORY ="PUT_SUBCATEGORY"
export const DELETE_CATEGORY ="DELETE_CATEGORY"
export const DELETE_SUB_CATEGORY ="DELETE_SUB_CATEGORY"







